### ISSUE TITLE
Error in { :    task 1 failed - "task 1 failed - "'x' must be an array of at least two dimensions""

### ISSUE THREAD

**Issue by ericlauren** [slamballais/QDECR#58] opened 2023-05-16 18:11 UTC
Hi, I am currently using QDECR to process some MRI data. I, unfortunately received the error code below in R and was wondering if you knew a solution? Any help would be greatly appreciated.

 Error in { : 
  task 1 failed - "task 1 failed - "'x' must be an array of at least two dimensions""

Our input is as follows (only defined variable in R environment is hemi = "lh"):

library(QDECR)
library(devtools)
library(magick)

Sys.setenv(FREESURFER_HOME = "/Applications/freesurfer/7.3.2")
# Set the FREESURFER_HOME environment variable
Sys.setenv(SUBJECTS_DIR = "pathname")
out <- qdecr_fastlm(qdecr_thickness ~ SmokingStatus + Sex,
                    data = read.csv("~/Desktop/rcedq_test/df.test.csv", header = TRUE, stringsAsFactors = FALSE),
                    id = "id",
                    hemi = hemi,
                    target = "fsaverage",
                    fwhm = 10,
                    mcz_thr = 0.001,
                    cwp_thr = 0.025,
                    mgh = NULL,
                    project = paste(hemi, "test.qdecr_thickness", sep="."),
                    dir_subj = "pathname",
                    dir_fshome = Sys.getenv("FREESURFER_HOME"),
                    dir_tmp = "~/Desktop/tmp",
                    clean_up = TRUE,
                    clean_up_bm = TRUE,
                    clobber = TRUE,
                    verbose = TRUE,
                    debug = FALSE,
                    n_cores = 4,
                    prep_fun = "prep_fastlm",
                    analysis_fun = "analysis_chunkedlm",
                    chunk_size = 1000)

I used the CSV file shown below:

id | SmokingStatus | Sex
B001_copy | Smoker | Male
B002_copy | Non-smoker | Female
B003_copy | Non-smoker | Male
B004_copy | Smoker | Female

I am new to R and coding in general if this a simple fix!

**Comment by slamballais** [comment] 2023-05-16 18:38
Hey @ericlauren, thanks for using QDECR! Just a quick question: is this happening during the loading of the vertex-wise data or in the analysis part? You can check this by looking in the logs that are printed.

Or, you can also just paste the log here and I'll have a look!

**Comment by ericlauren** [comment] 2023-05-16 20:19
Thank you for your quick response! It is during calculation of vertex-wise values. Not sure if you mean the console, but here is what r puts out:

------------------------------------------------------------ 
----------------------- QDECR v0.9.0 ----------------------- 
------------------------------------------------------------ 

Welcome to QDECR (v0.9.0)
Authors: Sander Lamballais & Ryan Muetzel
Website: www.qdecr.com
Repository: www.github.com/slamballais/QDECR

------------------------------------------------------------ 
--------------------- Integrity checks --------------------- 
------------------------------------------------------------ 

Checked all input arguments.

------------------------------------------------------------ 
------------------- Loading vertex data -------------------- 
------------------------------------------------------------ 




------------------------------------------------------------ 
------------------ Pre-analysis overview ------------------- 
------------------------------------------------------------ 

[input] Hemisphere:                    [lh]
[input] Project name:                  [lh.test.qdecr_thickness]
[input] Project final name:            [lh.lh.test.qdecr_thickness.thickness]
[input] Number of cores:               [4]
[input] Target:                        [fsaverage]
[input] dir_out_tree:                  [TRUE]
[input] clobber:                       [TRUE]
[input] fwhm:                          [10]
[paths] Subjects dir:                  [/Users/timothydurazzo/Desktop/rcedq_test/brave_test]
[paths] Freesurfer home dir:           [/Applications/freesurfer/7.3.2]
[paths] Temp dir:                      [~/Desktop/tmp]
[paths] Output dir:                    [/Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness]
[paths] Path to default mask:          [/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/QDECR/extdata/lh.fsaverage.cortex.mask.mgh]
[data ] N subjects:                    [4]
[data ] N data points:                 [4]
[data ] N datasets:                    [1]
[data ] Vertices loaded:               [163842]
[model] Model:                         [RcppEigen::fastLm]
[model] Vertex data:                   [thickness]
[model] Formula:                       [qdecr_thickness ~ SmokingStatus + Sex]
[model] Weights used:                  [No]
[mask ] Mask origin:                   [/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/QDECR/extdata/lh.fsaverage.cortex.mask.mgh]
[mask ] Masked vertices:               [149955]

------------------------------------------------------------ 
------------------- Vertex-wise analyses ------------------- 
------------------------------------------------------------ 




Converting coefficients, p-values, etc to .mgh format
Converting residual data to .mgh format

------------------------------------------------------------ 
------------------ Estimating smoothness ------------------- 
------------------------------------------------------------ 

Calculating smoothing for multiple testing correction.
mris_fwhm --i /Users/timothydurazzo/Desktop/tmp/lh.lh.test.qdecr_thickness.thickness_resid_backend.mgh --hemi lh --subject fsaverage --prune --cortex --dat /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/fwhm.dat --out-mask /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/finalMask.mgh
fsaverage lh white
Number of vertices 163842
Number of faces    327680
Total area         65417.000000
GroupSurface 82219.960938
AvgVtxArea       0.399269
AvgVtxDist       0.721953
StdVtxDist       0.195472
Found 149955 voxels in mask
Pruning voxels by thr: 1.175494e-38
Saving final mask to /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/finalMask.mgh
Polynomial detrending, order = 0
Computing spatial AR1 
ar1mn = 0.936612, ar1std = 0.209535, ar1max = 1
avg vertex dist 0.721953
avg vertex dist 0.721953
fwhm = 3.723976

------------------------------------------------------------ 
------------------ Clusterwise correction ------------------ 
------------------------------------------------------------ 



csd->threshsign = 0
thsign = abs, id = 0
version 7.3.2
hemi           = lh
srcid          = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.p.mgh 
srcsubjid      = fsaverage
srcsurf        = white
srcframe       = 0
thsign         = abs
thmin          = 3
thmax          = -1
fdr            = -1
minarea        = 0
xfmfile        = talairach.xfm
nth         = -1
outid    = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.masked.mgh MGH
ocnid    = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.ocn.mgh MGH
sumfile  = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.cluster.summary
subjectsdir    = /Users/timothydurazzo/Desktop/rcedq_test/brave_test
FixMNI = 0
Found 149429 vertices in mask
Found 149429 vertices in mask
Found 149429 points in clabel.
------------- XFM matrix (RAS2RAS) ---------------
/Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/mri/transforms/talairach.xfm
 1.00000   0.00000   0.00000   0.00000;
 0.00000   1.00000   0.00000   0.00000;
 0.00000   0.00000   1.00000   0.00000;
 0.00000   0.00000   0.00000   1.00000;
----------------------------------------------------
Reading source surface /Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/surf/lh.white
Done reading source surface
Reading annotation /Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/label/lh.aparc.annot
 supposed to be reproducible but seed not set
Computing metric properties
Loading source values
number of voxels in search space = 149429
Done loading source values (nvtxs = 163842)
overall max = inf at vertex 7
overall min = 0 at vertex 8
surface nvertices 163842
metric props tot surface area 65417.000000
group_avg_vtxarea_loaded 1
masked surface area 76236.875000
Computing voxel-wise significance
CSDpvalMaxSigMap(): found 149409/163842 above 0, max=inf
NOT Adjusting threshold for 1-tailed test
thminadj = 3
Searching for Clusters ...
thmin=3.000000 (3.000000), thmax=-1.000000 (-1), thsignid=0, minarea=0.000000
Found 1 clusters
Max cluster size 76236.875000
Pruning by CW P-Value 0.025
Saving thresholded output to  /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.masked.mgh
Saving cluster numbers to /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.ocn.mgh
Saving cluster pval /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.cluster.mgh
Constructing output annotation
Writing annotation /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack1.cache.th30.abs.sig.ocn.annot


csd->threshsign = 0
thsign = abs, id = 0
version 7.3.2
hemi           = lh
srcid          = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.p.mgh 
srcsubjid      = fsaverage
srcsurf        = white
srcframe       = 0
thsign         = abs
thmin          = 3
thmax          = -1
fdr            = -1
minarea        = 0
xfmfile        = talairach.xfm
nth         = -1
outid    = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.masked.mgh MGH
ocnid    = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.ocn.mgh MGH
sumfile  = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.cluster.summary
subjectsdir    = /Users/timothydurazzo/Desktop/rcedq_test/brave_test
FixMNI = 0
Found 149429 vertices in mask
Found 149429 vertices in mask
Found 149429 points in clabel.
------------- XFM matrix (RAS2RAS) ---------------
/Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/mri/transforms/talairach.xfm
 1.00000   0.00000   0.00000   0.00000;
 0.00000   1.00000   0.00000   0.00000;
 0.00000   0.00000   1.00000   0.00000;
 0.00000   0.00000   0.00000   1.00000;
----------------------------------------------------
Reading source surface /Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/surf/lh.white
Done reading source surface
Reading annotation /Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/label/lh.aparc.annot
 supposed to be reproducible but seed not set
Computing metric properties
Loading source values
number of voxels in search space = 149429
Done loading source values (nvtxs = 163842)
overall max = inf at vertex 33
overall min = 0 at vertex 8
surface nvertices 163842
metric props tot surface area 65417.000000
group_avg_vtxarea_loaded 1
masked surface area 76236.875000
Computing voxel-wise significance
CSDpvalMaxSigMap(): found 26402/163842 above 0, max=inf
NOT Adjusting threshold for 1-tailed test
thminadj = 3
Searching for Clusters ...
thmin=3.000000 (3.000000), thmax=-1.000000 (-1), thsignid=0, minarea=0.000000
Found 271 clusters
Max cluster size 1356.196899
Pruning by CW P-Value 0.025
Saving thresholded output to  /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.masked.mgh
Saving cluster numbers to /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.ocn.mgh
Saving cluster pval /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.cluster.mgh
Constructing output annotation
Writing annotation /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack2.cache.th30.abs.sig.ocn.annot


csd->threshsign = 0
thsign = abs, id = 0
version 7.3.2
hemi           = lh
srcid          = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.p.mgh 
srcsubjid      = fsaverage
srcsurf        = white
srcframe       = 0
thsign         = abs
thmin          = 3
thmax          = -1
fdr            = -1
minarea        = 0
xfmfile        = talairach.xfm
nth         = -1
outid    = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.masked.mgh MGH
ocnid    = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.ocn.mgh MGH
sumfile  = /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.cluster.summary
subjectsdir    = /Users/timothydurazzo/Desktop/rcedq_test/brave_test
FixMNI = 0
Found 149429 vertices in mask
Found 149429 vertices in mask
Found 149429 points in clabel.
------------- XFM matrix (RAS2RAS) ---------------
/Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/mri/transforms/talairach.xfm
 1.00000   0.00000   0.00000   0.00000;
 0.00000   1.00000   0.00000   0.00000;
 0.00000   0.00000   1.00000   0.00000;
 0.00000   0.00000   0.00000   1.00000;
----------------------------------------------------
Reading source surface /Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/surf/lh.white
Done reading source surface
Reading annotation /Users/timothydurazzo/Desktop/rcedq_test/brave_test/fsaverage/label/lh.aparc.annot
 supposed to be reproducible but seed not set
Computing metric properties
Loading source values
number of voxels in search space = 149429
Done loading source values (nvtxs = 163842)
overall max = inf at vertex 33
overall min = 0 at vertex 8
surface nvertices 163842
metric props tot surface area 65417.000000
group_avg_vtxarea_loaded 1
masked surface area 76236.875000
Computing voxel-wise significance
CSDpvalMaxSigMap(): found 27835/163842 above 0, max=inf
NOT Adjusting threshold for 1-tailed test
thminadj = 3
Searching for Clusters ...
thmin=3.000000 (3.000000), thmax=-1.000000 (-1), thsignid=0, minarea=0.000000
Found 246 clusters
Max cluster size 1256.331421
Pruning by CW P-Value 0.025
Saving thresholded output to  /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.masked.mgh
Saving cluster numbers to /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.ocn.mgh
Saving cluster pval /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.cluster.mgh
Constructing output annotation
Writing annotation /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness/stack3.cache.th30.abs.sig.ocn.annot

------------------------------------------------------------ 
-------------- Calculating vertex-wise values -------------- 
------------------------------------------------------------ 

Error in { : 
  task 1 failed - "task 1 failed - "'x' must be an array of at least two dimensions""

**Comment by slamballais** [comment] 2023-05-16 21:24
Ah, that is indeed not what I expected. I am currently traveling so I cannot easily access the system that I normally run tests on. I will give have a closer look next week, is that ok?

**Comment by ericlauren** [comment] 2023-05-16 21:26
Thanks so much, I would really appreciate that. I will wait to hear from you then!

**Comment by ericlauren** [comment] 2023-05-23 15:42
Hi, I wanted to check in and see if you had a chance to look over the bug?

**Comment by slamballais** [comment] 2023-05-23 19:05
Hey @ericlauren, sorry for the delay, it definitely slipped my mind. I did have a look, and I know where the error occurs, but given the information it's a bit unclear why it is happening.

In brief: For all the available scans we load in the vertex-wise measures. In this case, we load in the `.mgh` files for thickness. Next, we store all this data in a filebacked matrix, which is essentially an R object that is stored in a file. We do this, because the package was build with large datasets in mind, and this would help us with running it for larger datasets. However, it does mean that the file should remain on disk while the code is running.

This `mgh` data is stored somewhere in that matrix. At the very end of the QDECR call, I use that mgh matrix to calculate some extra information, like the mean thickness per vertex. In your case, it tries to run that code, but it implies that `x` (the mgh matrix) is not an array with two or more dimensions. This is odd, because it can only be a matrix. Furthermore, all the code before that works fine, implying that it was always properly a matrix. So, something weird is going on.

One possibility is that... the filebacked matrix is "gone". For example, it could be that the file gets deleted while you are running the code, or that it gets cleaned up for some reason. This is unlikely, unless you are touching `dir_tmp` while running QDECR, or if there is a quota (although, again, it would only occur in some edge case).

Another possibility is that some things changed in the packages that we use for all these filebacked matrices, and that I need to update the code. I'll have a look into that, but I doubt that that's the cause here.

I have a more practical solution. This filebacked matrix is stored in your `dir_tmp`: `~/Desktop/tmp`. I noticed that your `dir_out` is different: `/Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness`. Does that folder contain any output from the QDECR call? If so, is it possible to use that are your `dir_tmp`? That may actually fix the problem, in which case it could be related to your `~/Desktop/tmp`. 

I would run the following code:
```
data <- read.csv("~/Desktop/rcedq_test/df.test.csv", header = TRUE, stringsAsFactors = FALSE)

out <- qdecr_fastlm(qdecr_thickness ~ SmokingStatus + Sex,
  data = data,
  id = "id",
  hemi = hemi,
  project = paste(hemi, "test.qdecr_thickness", sep="."),
  dir_subj = "pathname",
  dir_tmp = "~/Desktop/tmp",
  clobber = TRUE,
  n_cores = 4
)
```

(Note: R works with default arguments. That means that a lot of the arguments in `qdecr_fastlm` have a default value. You can find the default values by typing `?qdecr_fastlm`. I have removed all the things where you specified the default value for an argument.)

**Comment by ericlauren** [comment] 2023-05-23 22:37
Thank you for your response. Unfortunately even using the above code, I received the same error: Error in { : 
  task 1 failed - "task 1 failed - "'x' must be an array of at least two dimensions""

There are many files created in the folder: /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness  each time the code is run. After changing the file path from  dir_tmp = "~/Desktop/tmp" to /Users/timothydurazzo/lh.lh.test.qdecr_thickness.thickness we still got the same error. Please let me know if you have any other suggestions.

**Comment by slamballais** [comment] 2023-05-24 14:44
Hmm, interesting. That is indeed a bit unexpected, also because I would have expected this problem to be associated with a problem that would occur earlier in the function, but I see no indication that this is happening. I don't know exactly where to look without touching any data myself.

My proposal is two-fold. One, I want to make a modified version of the package (this will take me a day or so) that will either fix the problem or move the error forward to the beginning of the call. Would you be willing to run that? I can't guarantee that it solves it.

Two, I would also be happy to set up a call to walk through it interactively and see if I can pinpoint the problem in that way. 

Thanks for your patience!

**Comment by ericlauren** [comment] 2023-05-24 16:52
Yes, we would be willing to run the modified version.  If that doesn't solve the problem we would be happy to meet with you on a call to see what is happening.  

Thank you very much for your help!

**Comment by slamballais** [comment] 2023-05-26 15:04
Alright, I created an alternative version of the package. Make sure that the previous version of QDECR is not loaded when you run the code below. Here is the code to install it:
```
remotes::install_github("slamballais/QDECR", ref = "test_ericlauren")
```

This will re-install QDECR. If everything went correctly, then the next time you run it you should see the message "Calculating vertex-wise summary values" under the "Loading vertex data" header. If this is the case, then one of three things will happen:
1. The error now happens immediately after that.
2. You don't get an error anymore and the function works.
3. You don't get an error there, but you get a new error at the end.

I think option 1 will happen, but option 2 may also occur. Either way, depending on what happens we can plan the next step. Again, thanks for your patience, I'm committed to helping you solve it.

**Comment by ericlauren** [comment] 2023-05-30 15:26
After reinstalling, option 1 occurred and we get the same error under "Calculating vertex-wise summary values".

**Comment by ericlauren** [comment] 2023-05-30 17:07
I was able to get it working with a larger data set! Not sure if there is a minimum requirement on data (our test set only had 4 rows) but the bug disappeared after adding a few more rows to the data set (17 rows total).

**Comment by slamballais** [comment] 2023-05-30 17:13
Oh, that's interesting! That was one of the things Ryan Muetzel (the other creator) and I were discussing, but after a few quick tests I did get the internal code to run with it, so this is unexpected to me. But good that it works! I'll leave the thread open in case you run into another problem related to this; feel free to reach out when needed. In the meantime I'll run some tests and modify the package to throw a better warning/error in this case.

**Comment by ericlauren** [comment] 2023-05-30 17:24
Thank you, we really appreciate your help! We will reach out if we encounter any new errors.

Many thanks,

Eric and Lauren

**Comment by ericlauren** [comment] 2023-06-21 15:41
Hi, I was wondering what method you use to highlight/remove outliers? Is there a built in system for quality control or a preferred method for scrubbing output data after running it through QDECR?

**Comment by ericlauren** [comment] 2023-06-21 15:50
Also, I was wondering what cluster size QDECR uses?

Thank you!!!

**Comment by slamballais** [comment] 2023-06-29 15:08
We do not highlight or remove outliers. It is possible to extract information on mean/SD per vertex or subject. I would need to write some convenient functions to pull those out, but they are stored here (if you have the analysis stored in the variable `vw`):

```
vw$post$mgh_description$vertex_mean
vw$post$mgh_description$vertex_sd
vw$post$mgh_description$subject_mean
vw$post$mgh_description$subject_sd
```

I hope the names speak for themselves.

The cluster sizes that are reported are simply the number of significant vertices. It is possible to get the mm2 per cluster if you want, but I haven't written it in a convenient way yet ;) The easiest way is to find your variable of interest by running `stacks(vw)` and then opening the corresponding file called (e.g., for stack 2) `stack2.cache.th30.abs.sig.cluster.summary`. Here you will find an mm2 column. I'll take it up for the next update of QDECR!

Edit: I noted the mm2 stuff as its [own issue](https://github.com/slamballais/QDECR/issues/63), as a reminder for myself to pick it up.

**Comment by ericlauren** [comment] 2023-07-11 22:04
Thank you so much!!! We will reach out if anything further comes up.

Best,

Eric and Lauren

**Comment by slamballais** [comment] 2023-07-12 07:01
I'm archiving this particular thread as the original problem has been solved and I'm cleaning up a bit, but if you have any particular questions, feel free to reach out to my e-mail (you can find it [here](https://github.com/slamballais/QDECR/blob/3903101038e8f550ec49fdaba8253a8a560c190a/DESCRIPTION#L7)).

**Closed as completed by slamballais** 2023-07-12 07:01 UTC
Labels: bug
